/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ColorPick: typeof import('./src/components/ColorPick.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    HighlightCode: typeof import('./src/components/HighlightCode.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
